apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: master-ip-pool
  namespace: metallb-system
spec:
  addresses:
  - 10.0.40.203-10.0.40.203
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - master-ip-pool
